### PR TITLE
Test Improvements

### PR DESCRIPTION
**Pull request by IanVS**
I added new feature to hopefully make development of server tests a little easier and quicker: run `make test-w` from the /server folder to run tests with a watcher that will re-fire if any changes are made to the test files.

The example test file now loads sails before executing the tests (and lowers after).  This will be necessary when tests are developed to do things like add users or verify ORM validations.

Initially I planned to have subfolders inside tests/unit for models, controllers, policies, etc.  After some thought, I think it makes more sense to apply a "pods" type philosophy to grouping the tests, meaning all the tests for users will go in tests/unit/users.Test.js.  I believe this follows BDD strategy a little more closely.

Lastly, I threw together a few ideas of additional tests to be created later (once I figure out how).  Trying to just brainstorm what kinds of tests might be useful at this point.

### CODE REVIEW

**Comment by mgenev** [comment]
thanks, that all seems great, I'll merge and they play with everything

**Comment by kriswill** [comment]
I'm not a fan of the Makefile.  I think `npm test` is even easier to type.

**Comment by kriswill** [comment]
In package.json:
```json
  "scripts": {
    "test": "mocha -R spec --ui bdd ./tests/unit/**/*.Test.js"
  },
```
to run:
```sh
$ npm test
$ # or to run with watch
$ npm test -- --watch
```

**Comment by kriswill** [comment]
stylistically, I would keep all file and folder names all lower-dashed.  `user.Test.js` -> `user-test.js`.

**Comment by mgenev** [comment]
houghts so far - seems like using async mocha in the afterAllTestsFinish and sails .lower is breaking, i removed the done's and it stopped failing
using sinon and chai together may be best using this https://github.com/domenic/sinon-chai

**Comment by IanVS** [comment]
Great comments and suggestions, thanks.

@kriswill do we lose anything by not using the runner.js?  Doesn't seem like it.  I agree it would be nicer without the Makefile, just couldn't figure out how.  Thanks.

@mgenev I was having problems with async until I modified the runner to remove `process.on('exit', function()`  When I took that out it would exit successfully.  Wonder if this is an apple / linux thing.  Sinon-chai looks cool.  Seems to also work correctly with proposed change to use command line mocha in the npm script.

**Comment by IanVS** [comment]
@kriswill The only reason I went with capitals was to stay consistent with SANE (https://github.com/artificialio/sane/blob/master/tests/runner.js) which it looks like I failed at, since there's no preceeding dot in those tests.  I'm not tied to any particular naming.  Can change to whatever everyone agrees is best.

**Comment by Globegitter** [comment]
Yeah @IanVS I actually prefer the `-` naming scheme. Just kinda started with camelCase, so either had to rename all of them (which I might do eventually :P) or carry on being consistent.

**Pull request merged**
