### PR TITLE
[WIP] Replace Bootstrap file uploader with ember-plupload component

### LINKED ISSUE #11: creating a album after having uploaded some photo, removes the upload
this happens because  it actually leaves the route. Make an implementation similar to the one at classmates where the modal is just a template loaded by an action with no route change.

### PR DESCRIPTION
**Pull request by IanVS**
Using `ember-plupload` should prevent the files queued for upload from being lost when an album is added, as the upload queue is maintained across routes. (fixes #11)

Remaining work:
- [x] Add submit button and action
- [x] Test against server API
- [x] Ensure that file deletion happens correctly
- [ ] Cache CORS preflight response
- [ ] Further UI/UX improvements
    - [x] Prevent upload button press without an album selected
    - [ ] Change behavior on hover when dragging in a file
    - [x] Make sure that file can be dragged to any location inside dropzone
- [ ] Extract component from template into ember component

### CODE REVIEW

**Comment by IanVS** [comment]
Looks like setting the max-age of the preflight CORS response is not yet possible in Sails: https://github.com/balderdashy/sails/issues/2345#issuecomment-100075124

**Comment by IanVS** [comment]
@mgenev my next step will likely be to extract the uploader/preview that we've created here into its own component.  Do you see any other changes I should make?

**Comment by mgenev** [comment]
I can't think of any changes right now. Great work so far. I'll probably end up styling as I think of ideas. If you have any you can feel free to revisit it any time.

**Comment by mgenev** [comment]
thinking of merging and adding improvements as go forward. any objections?

**Comment by IanVS** [comment]
Sure,  that's fine with me.

**Pull request merged**
