### PR TITLE
adds dynamic pages to app w/ documentation for the book

### PR DESCRIPTION
**Pull request by jamemackson**
At present, this is just a rough start for the documentation side of this PR.  More to come. :)

### CODE REVIEW

**Comment by mgenev** [comment]
look good so far :+1:

**Comment by jamemackson** [comment]
@mgenev I've got the CRUD functionality in place with this last round of commits.  I'm looking at how to integrate these with your header-nav component next which should really be the last piece we'll need.  

In https://github.com/hairbrained/gallery13 I just have the nav in the application.hbs file so I'll have to adjust what I did there to work with this component instead... I may have a few questions for you along the way however...

**Comment by mgenev** [comment]
I thought about this as well and I ended up making 2 separate components for nav - 1 public for CMS driven stuff that you just made and 1 for the admin stuff which my current header-nav is

**Comment by jamemackson** [comment]
@mgenev - a few quirks exist in the current version of this.  I noticed that on the `/s/page-manager` grid, it’s not reloading properly when a new page is created. The new page is there when you do a full refresh so it seems that the page-manager route is getting out of sync. and I think it’s probably the same issue but if I edit a page’s order, the page-manager grid doesn’t reflect this until the page is reloaded.

**Comment by jamemackson** [comment]
still todo:
- [ ] fix issues with `/s/page-manager` not syncing with edited and new pages
- [ ] allow access to get `/api/v1/pages` when user is not logged in
- [ ] add content to standard page layout 
- [ ] update the pages route to be a wildcard catch all and render the dynamic page
- [ ] add markdown-to-html add-on to convert markdown content.

**Comment by mgenev** [comment]
1is probably hardest, i'll have to look at that in detail, 4 is demonstrated in nodember, so pretty easy to port, 5 will be interesting to try out, the rest are trivial seems like

**Pull request merged**
